name: Daily Attendance Sync

on:
  schedule:
    # Runs every day at 18:00 (6 PM) IST. 
    # Change to '*/5 * * * *' ONLY if you want to run every 5 minutes.
    - cron: '30 12 * * *' 
  workflow_dispatch: # Allows you to manually click "Run workflow" in the Actions tab

jobs:
  sync_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Upgraded to 24 to fix deprecation warning

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper Agent
        # Pass secrets as environment variables to the script
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          ROLL_NO: ${{ secrets.ROLL_NO }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: node index.js